### ISSUE TITLE
not enough xbox

### ISSUE THREAD

**Issue by miiwhen** [davidsosa2022/Nintendo-TVii-Web#4]
not enough xbox. not enough xbox. not enough xbox. not enough xbox. not enough xbox. not enough xbox. not enough xbox. not enough xbox. not enough xbox. not enough xbox. not enough xbox. not enough xbox. not enough xbox. not enough xbox. not enough xbox. not enough xbox. not enough xbox. not enough xbox. not enough xbox. not enough xbox. not enough xbox. not enough xbox. not enough xbox. not enough xbox. not enough xbox. not enough xbox. not enough xbox. not enough xbox. not enough xbox. not enough xbox. not enough xbox. not enough xbox. not enough xbox. not enough xbox. not enough xbox. not enough xbox. not enough xbox. not enough xbox. not enough xbox. not enough xbox. not enough xbox. not enough xbox. not enough xbox. not enough xbox. not enough xbox. not enough xbox. not enough xbox. not enough xbox. not enough xbox. not enough xbox. not enough xbox. not enough xbox. not enough xbox. not enough xbox. not enough xbox. not enough xbox. not enough xbox. not enough xbox. not enough xbox. not enough xbox. not enough xbox. not enough xbox. not enough xbox. not enough xbox. not enough xbox. not enough xbox. not enough xbox. not enough xbox. not enough xbox. not enough xbox. not enough xbox. not enough xbox. not enough xbox. not enough xbox. not enough xbox.

**Comment by davidsosa2022** [comment]
Your dad.
