### ISSUE TITLE
how do i watch tv

### ISSUE THREAD

**Issue by miiwhen** [davidsosa2022/Nintendo-TVii-Web#5]
what is this site i never used this git hub please tell me what im doing is this the github guy well please teach me this site and how to get out of it 

how to leave github

wait thats not google

pelaesh lep

**Comment by miiwhen** [comment]
how to install minecraft 2023 no scam

**Comment by SomeonesGarbage** [comment]
im spongebob

**Comment by davidsosa2022** [comment]
please do serious issues, im tired of everyone thinking its a joke

**Comment by SomeonesGarbage** [comment]
ok
